
// const mongoose = require("mongoose");
const Recipes = [
    {name: "Chicken Alfredo", img: src="/chicken_alfredo.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: ["Bacon", "ipsum", "dolor", "amet", "pork"], directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},
    {name: "Puttanesca", img: src="/puttanesca.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Pastrami short loin alcatra cupim bresaola beef tongue frankfurter.", directions: "Kielbasa pork belly shank flank frankfurter filet mignon chuck turducken venison biltong cupim pig jerky ground round. Biltong drumstick tail pork, chicken tenderloin frankfurter jowl spare ribs. Picanha pig turkey shankle beef ribs pancetta porchetta tenderloin sausage ground round jerky chicken pastrami buffalo."},
    {name: "Tacos Al Pastor", img: src="/tacos.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet shankle in irure ham andouille veniam.", directions: "Consectetur anim chuck drumstick mollit sirloin tri-tip. Proident duis veniam id, turducken pork belly adipisicing tempor pig tri-tip consectetur aliquip labore shankle swine. Cupidatat minim commodo kielbasa kevin. Drumstick chuck in burgdoggen salami eiusmod, hamburger culpa in nostrud aute sirloin reprehenderit t-bone chicken"},
    {name: "Ribeye", img: src="/ribeye.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet pork belly kevin sirloin doner kielbasa burgdoggen pork chop tongue meatloaf ", directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},
    {name: "Sourdough", img: src="/sourdough.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Pastrami short loin alcatra cupim bresaola beef tongue frankfurter.", directions: "Kielbasa pork belly shank flank frankfurter filet mignon chuck turducken venison biltong cupim pig jerky ground round. Biltong drumstick tail pork, chicken tenderloin frankfurter jowl spare ribs. Picanha pig turkey shankle beef ribs pancetta porchetta tenderloin sausage ground round jerky chicken pastrami buffalo."},
    {name: "Thai Green Curry", img: src="/thaigreencurry.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet shankle in irure ham andouille veniam.", directions: "Consectetur anim chuck drumstick mollit sirloin tri-tip. Proident duis veniam id, turducken pork belly adipisicing tempor pig tri-tip consectetur aliquip labore shankle swine. Cupidatat minim commodo kielbasa kevin. Drumstick chuck in burgdoggen salami eiusmod, hamburger culpa in nostrud aute sirloin reprehenderit t-bone chicken"},
    {name: "Sushi", img: src="/sushi.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Pastrami short loin alcatra cupim bresaola beef tongue frankfurter.", directions: "Kielbasa pork belly shank flank frankfurter filet mignon chuck turducken venison biltong cupim pig jerky ground round. Biltong drumstick tail pork, chicken tenderloin frankfurter jowl spare ribs. Picanha pig turkey shankle beef ribs pancetta porchetta tenderloin sausage ground round jerky chicken pastrami buffalo."},
    {name: "Roasted Chicken", img: src="/RoastedChicken.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet shankle in irure ham andouille veniam.", directions: "Consectetur anim chuck drumstick mollit sirloin tri-tip. Proident duis veniam id, turducken pork belly adipisicing tempor pig tri-tip consectetur aliquip labore shankle swine. Cupidatat minim commodo kielbasa kevin. Drumstick chuck in burgdoggen salami eiusmod, hamburger culpa in nostrud aute sirloin reprehenderit t-bone chicken"},{name: "Pommes Duchess", img: src="/pommes_duchess.jpeg", ingredients: "Bacon ipsum dolor amet pork belly kevin sirloin doner kielbasa burgdoggen pork chop tongue meatloaf ", directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},
    {name: "Poached Eggs", img: src="/poachedegg.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Pastrami short loin alcatra cupim bresaola beef tongue frankfurter.", directions: "Kielbasa pork belly shank flank frankfurter filet mignon chuck turducken venison biltong cupim pig jerky ground round. Biltong drumstick tail pork, chicken tenderloin frankfurter jowl spare ribs. Picanha pig turkey shankle beef ribs pancetta porchetta tenderloin sausage ground round jerky chicken pastrami buffalo."},
    {name: "Chili", img: src="/chili.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet shankle in irure ham andouille veniam.", directions: "Consectetur anim chuck drumstick mollit sirloin tri-tip. Proident duis veniam id, turducken pork belly adipisicing tempor pig tri-tip consectetur aliquip labore shankle swine. Cupidatat minim commodo kielbasa kevin. Drumstick chuck in burgdoggen salami eiusmod, hamburger culpa in nostrud aute sirloin reprehenderit t-bone chicken"},
    {name: "Bacon Burgers", img: src="/burgers.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet pork belly kevin sirloin doner kielbasa burgdoggen pork chop tongue meatloaf ", directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},
    {name: "Braised Oxtail", img: src="/oxtail.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet shankle in irure ham andouille veniam.", directions: "Consectetur anim chuck drumstick mollit sirloin tri-tip. Proident duis veniam id, turducken pork belly adipisicing tempor pig tri-tip consectetur aliquip labore shankle swine. Cupidatat minim commodo kielbasa kevin. Drumstick chuck in burgdoggen salami eiusmod, hamburger culpa in nostrud aute sirloin reprehenderit t-bone chicken"},
    {name: "French Omelette with Herbs", img: src="/frenchomelette.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet pork belly kevin sirloin doner kielbasa burgdoggen pork chop tongue meatloaf ", directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},
    {name: "Savory Oats", img: src="/savoryoats.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet pork belly kevin sirloin doner kielbasa burgdoggen pork chop tongue meatloaf ", directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},
    {name: "Korean Veggie Pancakes", img: src="/koreanveg.jpeg", descriptions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami.", ingredients: "Bacon ipsum dolor amet pork belly kevin sirloin doner kielbasa burgdoggen pork chop tongue meatloaf ", directions: "Beef ribs tenderloin t-bone hamburger venison. Cupim shankle pork belly short ribs jowl pork fatback leberkas ham hock ground round chislic beef beef ribs. Leberkas brisket buffalo, andouille kielbasa cupim spare ribs boudin ground round burgdoggen. Pork loin cow beef pastrami frankfurter, filet mignon alcatra cupim shank kielbasa ham hock sausage. Shankle boudin beef ribs chuck prosciutto salami."},

];

// const recipesSchema = new mongoose.Schema (
//     {
//         body: {type: String, required: true}
//     },
//     {
//         timmestamps: true,
//     }
// );

// const Recipes = mongoose.model("Recipe", recipesSchema);


module.exports = Recipes;



